# Generated by Django 5.1.4 on 2024-12-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_mesa', models.FloatField(default=0)),
                ('precio', models.FloatField(default=0)),
                ('activa', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='llamadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_mesa', models.IntegerField(default=0)),
                ('hora', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_cuenta', models.FloatField(default=0)),
                ('precio', models.FloatField(default=0)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField(default='')),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('categoria', models.CharField(default='tapas', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='productos_pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_cuenta', models.FloatField()),
                ('identificador_pedido', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.FloatField()),
                ('num', models.IntegerField()),
                ('activa', models.BooleanField(default=False)),
            ],
        ),
    ]
